In [1]:
import torch

## 1.索引与切片方法：

### 1.1 一般索引：

In [2]:
a = torch.rand(4,3,28,28)

In [3]:
a[0]

tensor([[[0.6412, 0.7649, 0.6520,  ..., 0.6787, 0.8154, 0.0746],
         [0.5678, 0.9637, 0.9967,  ..., 0.3281, 0.9379, 0.5122],
         [0.4621, 0.7104, 0.3306,  ..., 0.2900, 0.4956, 0.4820],
         ...,
         [0.2847, 0.5402, 0.6430,  ..., 0.6790, 0.8000, 0.3977],
         [0.3529, 0.9373, 0.7722,  ..., 0.0242, 0.6721, 0.5983],
         [0.0337, 0.3073, 0.3344,  ..., 0.5249, 0.0822, 0.3789]],

        [[0.8477, 0.1752, 0.0516,  ..., 0.3909, 0.0381, 0.3783],
         [0.8935, 0.1897, 0.7621,  ..., 0.7082, 0.3384, 0.8146],
         [0.6321, 0.6241, 0.4947,  ..., 0.9310, 0.7682, 0.8642],
         ...,
         [0.9591, 0.0622, 0.0520,  ..., 0.3043, 0.0597, 0.6045],
         [0.6917, 0.6232, 0.5866,  ..., 0.9370, 0.0047, 0.9454],
         [0.8640, 0.2429, 0.8214,  ..., 0.0614, 0.0395, 0.6852]],

        [[0.9697, 0.1449, 0.1239,  ..., 0.4752, 0.7060, 0.9259],
         [0.4737, 0.2422, 0.2605,  ..., 0.5286, 0.2266, 0.2649],
         [0.2405, 0.6473, 0.9947,  ..., 0.2582, 0.8715, 0.

In [4]:
a[0].shape

torch.Size([3, 28, 28])

In [5]:
a[0,0]

tensor([[0.6412, 0.7649, 0.6520, 0.3188, 0.8737, 0.7132, 0.5936, 0.5943, 0.4706,
         0.5214, 0.1863, 0.0155, 0.5523, 0.1712, 0.6090, 0.3881, 0.1392, 0.6453,
         0.3707, 0.9058, 0.7579, 0.5323, 0.6246, 0.0431, 0.6448, 0.6787, 0.8154,
         0.0746],
        [0.5678, 0.9637, 0.9967, 0.9159, 0.1179, 0.2607, 0.5565, 0.9291, 0.3648,
         0.8886, 0.8571, 0.2662, 0.3373, 0.8637, 0.0100, 0.3069, 0.8793, 0.2380,
         0.0458, 0.1191, 0.4861, 0.1081, 0.1966, 0.1138, 0.2788, 0.3281, 0.9379,
         0.5122],
        [0.4621, 0.7104, 0.3306, 0.0694, 0.3016, 0.9337, 0.6811, 0.5454, 0.5452,
         0.8557, 0.6028, 0.1270, 0.3972, 0.4172, 0.5956, 0.9371, 0.3068, 0.2174,
         0.8037, 0.3877, 0.3956, 0.3316, 0.2043, 0.9046, 0.1525, 0.2900, 0.4956,
         0.4820],
        [0.9223, 0.1107, 0.6638, 0.9609, 0.5096, 0.6365, 0.0071, 0.4901, 0.0412,
         0.0361, 0.8102, 0.3377, 0.4733, 0.3532, 0.7874, 0.0153, 0.2656, 0.4935,
         0.5072, 0.5754, 0.9861, 0.6290, 0.8871, 0.2874

In [6]:
a[0,0].shape

torch.Size([28, 28])

In [7]:
a[0,0,2,4]

tensor(0.3016)

In [8]:
a[0,0,2,4].shape

torch.Size([])

### 1.2 一般的切片索引：

In [9]:
a.shape

torch.Size([4, 3, 28, 28])

In [10]:
# 默认从dim 0开始索引
a[:2].shape

torch.Size([2, 3, 28, 28])

In [11]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [12]:
a[:2,1,:,:].shape

torch.Size([2, 28, 28])

In [13]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

### 1.3 使用step进行索引：

In [14]:
a.shape

torch.Size([4, 3, 28, 28])

In [15]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [16]:
# 通过设置step（步长），进行隔行采样
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [17]:
# 下面的方式等同于上面的方式
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

### 1.4 通过特定下标进行索引：

In [18]:
a.shape

torch.Size([4, 3, 28, 28])

In [19]:
# 索引dim 0的第0和第2个数据
a.index_select(dim=0 , index=torch.tensor([0,2] , dtype=torch.long)).shape

torch.Size([2, 3, 28, 28])

In [20]:
# 索引dim 1的第0和第2个数据
a.index_select(1,torch.tensor([0,2])).shape

torch.Size([4, 2, 28, 28])

In [21]:
# 索引dim 2的第0-7的8个数据
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

### 1.5 通过...(任意多维度)进行索引：

In [22]:
a.shape

torch.Size([4, 3, 28, 28])

In [23]:
# 此种情况代表四个维度都取
a[...].shape

torch.Size([4, 3, 28, 28])

In [24]:
# dim 0取第0个，后面3个dim都取
a[0,...].shape

torch.Size([3, 28, 28])

In [25]:
# dim 0全取，dim 1取第1个，后面2个dim都取
a[:,1,...].shape

torch.Size([4, 28, 28])

In [26]:
# 最后一个dim取第0和第1，前面的dim都取
a[...,:2].shape

torch.Size([4, 3, 28, 2])

### 1.6 通过mask（掩码）进行索引：

In [27]:
x = torch.randn(3,4)
x

tensor([[ 1.0152,  0.6072, -0.3388,  2.1547],
        [-0.0741,  0.9814,  1.1197, -1.0260],
        [ 1.5267, -0.7220,  0.0235,  0.6595]])

In [28]:
# 得到＞0.5的数据的掩码
mask = x.ge(0.5) # 等价于x>0.5
mask

tensor([[ True,  True, False,  True],
        [False,  True,  True, False],
        [ True, False, False,  True]])

In [29]:
# 使用torch.masked_select()函数选择
torch.masked_select(x,mask)

tensor([1.0152, 0.6072, 2.1547, 0.9814, 1.1197, 1.5267, 0.6595])

In [30]:
# 得到的数据会被打平（dim为1）
torch.masked_select(x,mask).shape

torch.Size([7])

In [31]:
x[mask]

tensor([1.0152, 0.6072, 2.1547, 0.9814, 1.1197, 1.5267, 0.6595])

In [32]:
x[mask].shape

torch.Size([7])

### 1.7 通过take（掩码）进行索引：

In [33]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
x.shape

torch.Size([3, 3])

In [35]:
torch.take(x,torch.tensor([0,2,5,7]))

tensor([1, 3, 6, 8])

## 2.应用举例：

### 索引和切片操作常用于从数据集中提取特定的样本或特征

In [36]:
# 假设有一个形状为(1000, 10, 28, 28)的数据集，表示1000个样本，每个样本有10个通道，每个通道是28x28的图像  
data = torch.rand(1000, 10, 28, 28)  

# 提取第5个样本的所有通道  
sample = data[4]  # 形状为(10, 28, 28)  

# 提取前100个样本的第1个通道  
channel = data[:100, 0]  # 形状为(100, 28, 28)

In [37]:
sample.shape

torch.Size([10, 28, 28])

In [38]:
channel.shape

torch.Size([100, 28, 28])

### 索引和切片操作可以用于实现各种数据增强技术，如随机裁剪、翻转等

In [39]:
# 随机裁剪一个图像  
image = torch.rand(3, 224, 224)  # 假设有一个3通道224x224的图像  
crop_size = (200, 200)  
start = (torch.rand(2) * (224 - 200)).long()  # 随机计算裁剪的起始位置  
cropped_image = image[:, start[0]:start[0]+crop_size[0], start[1]:start[1]+crop_size[1]]

In [40]:
cropped_image.shape

torch.Size([3, 200, 200])

### 索引和切片操作可以用于提取一个batch中的样本，或者从模型的输出中提取特定的信息

In [41]:
# 假设模型的输出是一个形状为(batch_size, num_classes)的Tensor  
outputs = torch.rand(64, 10)  

# 提取第一个样本的输出  
first_output = outputs[0]  

# 提取一个batch中所有样本的第3个类别的输出  
third_class_outputs = outputs[:, 2]

In [42]:
first_output.shape

torch.Size([10])

In [43]:
third_class_outputs.shape

torch.Size([64])