In [1]:
import torch

## 1.模块级函数（Module-level functions）：

In [2]:
# rand()方法随机的使用[0,1)的均值分布进行随机生成
torch.rand(3,3)

tensor([[0.1833, 0.7075, 0.9843],
        [0.3576, 0.4478, 0.0301],
        [0.6581, 0.6010, 0.4836]])

## 2.张量级方法（Tensor-level methods）：

In [3]:
a = torch.rand(4,1,28,28)

In [4]:
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
# replace方法——改变张量形状
a.reshape(4,28*28)

tensor([[0.9921, 0.3521, 0.6774,  ..., 0.7669, 0.2250, 0.5316],
        [0.1652, 0.7287, 0.5843,  ..., 0.2293, 0.9261, 0.0171],
        [0.2719, 0.7430, 0.6142,  ..., 0.1916, 0.7863, 0.4638],
        [0.8349, 0.0181, 0.5342,  ..., 0.0179, 0.9114, 0.7160]])

In [6]:
a.reshape(4,28*28).shape

torch.Size([4, 784])

### 2.1 普通方法 / inplace方法：

In [7]:
a = torch.ones(3)

In [8]:
a

tensor([1., 1., 1.])

In [9]:
b = torch.ones(3)

In [10]:
b

tensor([1., 1., 1.])

In [11]:
# 普通方法
b.add(a)

tensor([2., 2., 2.])

In [12]:
b

tensor([1., 1., 1.])

In [13]:
# inplace方法
b.add_(a)

tensor([2., 2., 2.])

In [14]:
b

tensor([2., 2., 2.])