In [1]:
import numpy as np
import torch

In [2]:
# 忽略警告
import warnings
warnings.filterwarnings("ignore")

## 1.从numpy数组创建：

In [3]:
# 创建一个 NumPy 数组  
a = np.array([2,3.3])

In [4]:
# 转换为 Tensor
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [5]:
# 创建一个 NumPy 数组  
b = np.array([[1,2,3,4],
              [5,6,7,8]])

In [6]:
# 转换为 Tensor
torch.from_numpy(b)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)

## 2.从python的list创建：

### 1.1 torch.tensor()：

In [7]:
# 会尝试推断数据的类型
torch.tensor([2,3])

tensor([2, 3])

In [8]:
torch.tensor([2,3]).type()

'torch.LongTensor'

In [9]:
torch.tensor([[2,3.3],[5,6.6]])

tensor([[2.0000, 3.3000],
        [5.0000, 6.6000]])

In [10]:
torch.tensor([[2,3.3],[5,6.6]]).type()

'torch.FloatTensor'

In [11]:
# 输入数据也可以是ndarray
torch.tensor(np.array([2,3.3]))

tensor([2.0000, 3.3000], dtype=torch.float64)

In [12]:
torch.tensor(np.array([2,3.3])).type()

'torch.DoubleTensor'

### 1.2 torch.Tensor()：

In [13]:
# 默认数据类型为FloatTensor
torch.Tensor([2,3])

tensor([2., 3.])

In [14]:
torch.Tensor([2,3]).type()

'torch.FloatTensor'

In [15]:
torch.Tensor([[2,3.3],[5,6.6]])

tensor([[2.0000, 3.3000],
        [5.0000, 6.6000]])

In [16]:
torch.Tensor([[2,3.3],[5,6.6]]).type()

'torch.FloatTensor'

In [17]:
# 输入数据也可以是ndarray
torch.Tensor(np.array([2,3.3]))

tensor([2.0000, 3.3000])

In [18]:
torch.Tensor(np.array([2,3.3])).type()

'torch.FloatTensor'

## 3.创建未初始化的Tensor：

In [19]:
# empty()方法接收的是shape
torch.empty(2,3)

tensor([[3.3975e+21, 1.6517e-04, 2.1763e-04],
        [2.1277e+23, 4.1202e-11, 4.2330e+21]])

In [20]:
# Tensor()方法接收的也是shape
torch.Tensor(2,3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.9874e-44]])

## 4.将tensor赋值为同一个元素：

In [21]:
# 创建一个形状为 (2, 3) 的 tensor，并填充值 7 
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [22]:
torch.full([],7)

tensor(7)

In [23]:
torch.full([1],7)

tensor([7])

## 5.随机生成：

In [24]:
# .rand()方法随机的使用[0,1)的均值分布进行随机生成
torch.rand(3,3)

tensor([[0.0575, 0.5006, 0.9726],
        [0.9132, 0.9016, 0.5111],
        [0.8967, 0.3880, 0.0515]])

In [25]:
# .rand_like()方法接收的是一个tensor，它是将tensor的shape读出来之后在未给rand()
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.0312, 0.3102, 0.8281],
        [0.4740, 0.4782, 0.0628],
        [0.3599, 0.5479, 0.4212]])

In [26]:
# .randint(min,max,shape)方法使用自定义的数据空间，其中取值范围为[min,max）,shape接收的是一个列表
torch.randint(1,10,[3,3])

tensor([[2, 9, 4],
        [2, 1, 2],
        [3, 3, 5]])

In [27]:
# .randn()为N(0,1)，即均值为0，方差为1
torch.randn(3,3)

tensor([[-0.1111, -1.6330, -0.7691],
        [ 0.6402,  2.0426,  1.1718],
        [-1.0552,  0.5367, -0.2874]])

In [28]:
# .normal(u,std)方法可以自定义取值和方差，但是使用起来不是很方便
torch.normal(mean=torch.full([10],0.),std=torch.arange(1,0,-0.1))

tensor([ 2.0074, -0.4380, -0.4660,  0.5503,  0.0223, -0.4709,  0.0156,  0.3456,
         0.4640, -0.0428])

## 6.序列生成：

In [29]:
# 创建一个从0到10（不包含10）的等差序列，步长为1 
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# 创建一个从0到10（不包含10）的等差序列，步长为2
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [31]:
# .range()方法会被弃用，使用.arange()方法替代
torch.range(0,10)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
# 创建一个从0到10的等间隔数值序列，包含5个元素 
torch.linspace(0,10,steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [33]:
# 创建一个从0到10的等间隔数值序列，包含10个元素 
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [34]:
# 创建一个从10^0到10^1的均匀间隔数字序列，包含4个元素
torch.logspace(0,1,steps=4)

tensor([ 1.0000,  2.1544,  4.6416, 10.0000])

In [35]:
# 创建一个从2^0到2^3的序列，包含4个元素
torch.logspace(0,1,steps=4,base=2)

tensor([1.0000, 1.2599, 1.5874, 2.0000])

## 7.全0、全1、单位矩阵：

In [36]:
# 创建一个3x3的全零张量 
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [37]:
# 创建一个3x2的全为1的张量 
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
# 创建一个与a形状相同的全一张量
a = torch.rand(3,3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
# 创建一个3x3的单位矩阵
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
# eye()方法当给定的shape不对应时，多余的会以0填充
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [41]:
# eye()方法只能接受一个或两个数据，也就是说不能生产更高维的数据
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## 8.随机排列：

In [42]:
# 返回一个0到9的10个整数的随机排列张量
torch.randperm(10)

tensor([2, 8, 4, 1, 7, 6, 9, 5, 3, 0])