In [1]:
import numpy as np
import torch

## 1.torch.from_numpy()：

In [2]:
# 创建一个 NumPy 数组  
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])  

In [3]:
# 将 NumPy 数组转换为 PyTorch 张量  
tensor = torch.from_numpy(numpy_array)  

In [4]:
# 修改 PyTorch 张量的一个元素  
tensor[0, 0] = 100

In [5]:
# NumPy 数组也发生了改变  
numpy_array

array([[100,   2,   3],
       [  4,   5,   6]])

In [6]:
# 同样地，如果修改 NumPy 数组，PyTorch 张量也会改变  
numpy_array[1, 1] = 200  
tensor

tensor([[100,   2,   3],
        [  4, 200,   6]], dtype=torch.int32)

### 1.1 创建不共享内存的独立张量：

#### torch.tensor()：

In [7]:
# 创建一个 NumPy 数组  
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 创建一个与原始 NumPy 数组不共享内存的新张量  
tensor_independent = torch.tensor(numpy_array, dtype=torch.float32)  # 可以指定数据类型 
tensor_independent

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
numpy_array[1, 1] = 200  
numpy_array

array([[  1,   2,   3],
       [  4, 200,   6]])

In [10]:
tensor_independent

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### copy() + torch.from_numpy()：

In [11]:
# 创建一个 NumPy 数组  
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 创建 NumPy 数组副本，然后再转换为张量  
numpy_array_copy = numpy_array.copy()  
tensor_independent = torch.from_numpy(numpy_array_copy)
tensor_independent

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [13]:
numpy_array[1, 1] = 200  
numpy_array

array([[  1,   2,   3],
       [  4, 200,   6]])

In [14]:
tensor_independent

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 2.torch.numpy()：

In [15]:
# 假设有一个在 CPU 上的 PyTorch 张量  
cpu_tensor = torch.tensor([1, 2, 3])  

In [16]:
# 使用 .numpy() 将其转换为 Numpy 数组  
numpy_array_from_tensor = cpu_tensor.numpy()  

In [17]:
# 修改 Numpy 数组  
numpy_array_from_tensor[0] = 10  

In [18]:
# 原始的 PyTorch 张量也发生了改变  
cpu_tensor

tensor([10,  2,  3])

### 2.1 张量在 GPU 上：

In [19]:
# 假设有一个在 GPU 上的 PyTorch 张量  
gpu_tensor = torch.tensor([1, 2, 3] , device="cuda")

In [20]:
# 这会抛出错误   
numpy_array_from_gpu_tensor = gpu_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [21]:
# 正确的做法  
numpy_array_from_gpu_tensor = gpu_tensor.to(device="cpu").numpy()
numpy_array_from_gpu_tensor

array([1, 2, 3], dtype=int64)