In [1]:
import torch

## 1.Tensor的数据类型：

### torch.set_default_tensor_type()

In [2]:
tensor = torch.rand(2,3)
tensor

tensor([[0.0348, 0.9351, 0.7575],
        [0.7050, 0.1851, 0.7556]])

In [3]:
tensor.dtype

torch.float32

In [4]:
# 将默认数据类型设置为float64
torch.set_default_tensor_type('torch.DoubleTensor')

In [5]:
tensor_new = torch.rand(2,3)
tensor_new

tensor([[0.1881, 0.0584, 0.2432],
        [0.0635, 0.9154, 0.6279]])

In [6]:
tensor_new.dtype

torch.float64

In [7]:
# 恢复默认的数据类型
torch.set_default_tensor_type('torch.FloatTensor')

## 2.指定和更改Tensor的数据类型：

### 2.1 创建时指定数据类型：

In [8]:
# 创建一个float32类型的Tensor  
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
float_tensor.dtype

torch.float32

In [9]:
# 创建一个int64类型的Tensor  
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
int64_tensor.dtype

torch.int64

In [10]:
# 使用.type()方法可以返回一个str
float_tensor.type()

'torch.FloatTensor'

In [11]:
# 使用isinstance()方法进行数据类型检验
isinstance(int64_tensor , torch.LongTensor)

True

### 2.2 更改现有Tensor的数据类型：

In [12]:
# 将float32转换为float64类型  
double_tensor = float_tensor.double()
double_tensor.dtype

torch.float64

In [13]:
# 将int64转换为int16类型  
int16_tensor = int64_tensor.short()
int16_tensor.dtype

torch.int16

#### to()方法

In [14]:
# 将float32转换为float16类型  
half_tensor = float_tensor.to(torch.half)
half_tensor.dtype

torch.float16

#### type()方法

In [15]:
# 将int64转换为int32类型  
int32_tensor = int64_tensor.type(torch.int)
int32_tensor.dtype

torch.int32

#### 在操作中输入多种数据类型时，输入会自动向较大类型转换

In [16]:
tensor_1 = torch.rand(5 , dtype=torch.float64)
tensor_1

tensor([0.3345, 0.4079, 0.4873, 0.7552, 0.7650], dtype=torch.float64)

In [17]:
tensor_2 = tensor_1.to(dtype=torch.int16)
tensor_2

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [18]:
tensor_3 = tensor_1 + tensor_2
tensor_3

tensor([0.3345, 0.4079, 0.4873, 0.7552, 0.7650], dtype=torch.float64)

In [19]:
tensor_3.dtype

torch.float64